name: Deploy to Cloud Run

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: '${{ secrets.SCRT_KEY_CLD }}'

    - name: Set up gcloud CLI
      uses: google-github-actions/setup-gcloud@v2

    - name: Configure Docker for Artifact Registry
      run: gcloud auth configure-docker

    - name: Build and Push Docker image
      run: |
        IMAGE=us-central1-docker.pkg.dev/my-task-01-470709/cloud-run-repo/python-app:latest
        gcloud artifacts repositories create cloud-run-repo --repository-format=docker --location=us-central1 --quiet || true
        docker build -t $IMAGE .
        docker push $IMAGE

    - name: Deploy to Cloud Run
      run: |
        IMAGE=us-central1-docker.pkg.dev/my-task-01-470709/cloud-run-repo/python-app:latest
        gcloud run deploy python-app \
          --image $IMAGE \
          --platform managed \
          --region us-central1 \
          --allow-unauthenticated \
          --quiet
